[env:esp12e]
platform = espressif8266@4.2.1
board = esp12e
framework = arduino

; --- 硬件配置（匹配你的芯片） ---
monitor_speed = 115200
upload_speed = 460800
;upload_port = COM5    ; 注释掉让 PlatformIO 自动检测端口

; Flash 参数：DIO 模式，26MHz 晶振，4MB
board_build.flash_mode = dio
board_build.f_flash = 26000000L
board_build.ldscript = eagle.flash.4m2m.ld

; --- 调试与日志（注释掉可关闭底层 WiFi 日志噪音） ---
;build_flags =
;    -DDEBUG_ESP_PORT=Serial
;    -DDEBUG_ESP_CORE
;    -DDEBUG_ESP_WIFI
;    -DDEBUG_ESP_HTTP_CLIENT
;    -DCORE_DEBUG_LEVEL=3

; --- 依赖库（按需添加，锁定版本） ---
lib_deps =
    knolleary/PubSubClient@2.8
